server:
  port: 7083
  
spring:      
  application:
    name: UserJobPOC
  datasource:
    url: jdbc:mysql://localhost:3306/localhost
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    
    servlet:
       multipart:
         max-file-size:2MB
         max-request-size:2MB
    
         
    
   
          